# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:7

stages:
  - lint
  - build
  - test

lint:
  stage: lint
  script:
    - yarn
    - npm run lint

test:
  stage: test
  script:
    - yarn
    - npm run unit

build:
  stage: build
  script:
    - yarn
    - npm run build
  artifacts:
    paths:
    - dist/
